const actionTypes = {
  ADD_NEXT_MARK: 'ADD_NEXT_MARK',
  UPDATE_MARK_FIELD: 'UPDATE_MARK_FIELD',
  LOAD_MARK: 'LOAD_MARK',
  LOAD_MARKS: 'LOAD_MARKS',
  LOAD_NOTE: 'LOAD_NOTE',
  SET_CURRENT_MARK: 'SET_CURRENT_MARK',
  DESTROY_MARK: 'DESTROY_MARK',
  OPEN_NEW_NOTE: 'OPEN_NEW_NOTE',
  CLOSE_NEW_NOTE: 'CLOSE_NEW_NOTE',
  CHANGE_NEW_NOTE: 'CHANGE_NEW_NOTE',
  CREATE_NEW_NOTE: 'CREATE_NEW_NOTE',
  SET_VIDEO_TIME: 'SET_VIDEO_TIME',
  COMPLETED_TIME_UPDATE: 'COMPLETED_TIME_UPDATE',
  CHANGE_NOTE_ORDER: 'CHANGE_NOTE_ORDER',
}

export default actionTypes
