const actionTypes = {
  ADD_NEXT_MARK: 'ADD_NEXT_MARK',
  UPDATE_MARK_FIELD: 'UPDATE_MARK_FIELD',
  LOAD_MARKS: 'LOAD_MARKS',
  LOAD_MARK: 'LOAD_MARK',
  DESTROY_MARK: 'DESTROY_MARK',
  NEW_NOTE_OPEN: 'NEW_NOTE_OPEN',
}

export default actionTypes
