// TODO XXX: Should separate these into sections By Resource
const actionTypes = {
  // TODO XXX: Update typically signifies that it's been updated in the DB,
  //  Should change `Update` to probably `Change` to signify that it's
  //  just a local change and hasn't been persisted to DB yet
  MARK_SESSIONS: {
    SET_CURRENT: 'SET_CURRENT_MARK_SESSION',
    OPEN_CURRENT_EDITOR: 'OPEN_CURRENT_EDITOR_MARK_SESSION',
    CLOSE_CURRENT_EDITOR: 'CLOSE_CURRENT_EDITOR_MARK_SESSION',
    LOAD: 'LOAD_MARK_SESSIONS',
    UPDATE_FIELD: 'UPDATE_MARK_SESSION_FIELD',
    UPDATE: 'UPDATE_MARK_SESSION',
    CREATE: 'CREATE_MARK_SESSION',
  },
  MARK_WIDGETS: {
    OPEN_NEW_EDITOR: 'OPEN_NEW_MARK_WIDGET_EDITOR',
    OPEN_EDITOR: 'OPEN_MARK_WIDGET_EDITOR',
    OPEN_MANUAL_INPUTTER: 'OPEN_MARK_WIDGET_FORM_MANUAL_INPUTTER',
    CLOSE_NEW_EDITOR: 'CLOSE_NEW_MARK_WIDGET_EDITOR',
    CLOSE_EDITOR: 'CLOSE_MARK_WIDGET_EDITOR',
    CLOSE_MANUAL_INPUTTER: 'CLOSE_MARK_WIDGET_FORM_MANUAL_INPUTTER',
    LOAD: 'LOAD_MARK_WIDGETS',
    LOAD_MARKS: 'LOAD_MARKS_INTO_WIDGET',
    UPDATE_FIELD: 'UPDATE_MARK_WIDGET_FIELD',
    UPDATE: 'UPDATE_MARK_WIDGET',
    CREATE: 'CREATE_MARK_WIDGET',
    DESTROY: 'DESTROY_MARK_WIDGET',
  },
  MARKS: {
    ADD_MARK: 'ADD_MARK',
    ADD_NEXT_MARK: 'ADD_NEXT_MARK',
    UPDATE_MARK_FIELD: 'UPDATE_MARK_FIELD',
    UPDATE_MARK: 'UPDATE_MARK',
    LOAD_MARK: 'LOAD_MARK',
    LOAD_MARKS: 'LOAD_MARKS',
    DESTROY_MARK: 'DESTROY_MARK',
    OPEN_MANY_MARK_INPUT: 'OPEN_MANY_MARK_INPUT',
    CLOSE_MANY_MARK_INPUT: 'CLOSE_MANY_MARK_INPUT',
    CLEAR_MANY_MARK_INPUT: 'CLEAR_MANY_MARK_INPUT',
    UPDATE_MANY_MARK_INPUT: 'UPDATE_MANY_MARK_INPUT',
    SUBMIT_MANY_MARK_INPUT: 'SUBMIT_MANY_MARK_INPUT',
    EDIT_MARK: 'EDIT_MARK',
    CLOSE_MARK_FORM: 'CLOSE_MARK_FORM',
    SET_CURRENT_MARK: 'SET_CURRENT_MARK',
    ORGANIZE_MARKS: 'ORGANIZE_MARKS',
  },
  NOTES: {
    LOAD_NOTE: 'LOAD_NOTE',
    OPEN_NEW_NOTE: 'OPEN_NEW_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    CLOSE_NEW_NOTE: 'CLOSE_NEW_NOTE',
    CHANGE_NEW_NOTE: 'CHANGE_NEW_NOTE', // TODO XXX: Should be handleChange
    CREATE_NEW_NOTE: 'CREATE_NEW_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',
    DESTROY_NOTE: 'DESTROY_NOTE',
  },
  NOTE_TAKER: {
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    SET_VIDEO_TIME: 'SET_VIDEO_TIME',
    COMPLETED_TIME_UPDATE: 'COMPLETED_TIME_UPDATE',
    CHANGE_NOTE_ORDER: 'CHANGE_NOTE_ORDER',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  }
}

export default actionTypes
